---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ecommerce
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-shopping
  annotations:
    jenkins.io/job-full-name: "departmentFoo:online-shopping"
spec:
  type: website
  lifecycle: experimental
  owner: ecommerce-owner
  system: ecommerce
  consumesApis: [payment-api, hello-world-trpc]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api
spec:
  type: grpc
  lifecycle: experimental
  owner: abc-bank
  system: banking
  definition: |
    syntax = "proto3";

    service Payment {
      rpc Payment (PaymentMessage) returns (PaymentMessage) {};
    }

    message PaymentMessage {
      string example = 1;
    };
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ecommerce-user
spec:
  memberOf: [ecommerce-owner]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ecommerce-owner
spec:
  type: team
  children: []

