---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: banking
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-banking
  annotations:
    jenkins.io/job-full-name: "departmentFoo:online-banking"
spec:
  type: website
  lifecycle: experimental
  owner: abc-bank
  system: banking
  providesApis: [payment-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
spec:
  type: service
  lifecycle: experimental
  owner: abc-bank
  system: Banking
  providesApis: [payment-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api
spec:
  type: grpc
  lifecycle: experimental
  owner: abc-bank
  system: banking
  definition: |
    syntax = "proto3";

    service Payment {
      rpc Payment (PaymentMessage) returns (PaymentMessage) {};
    }

    message PaymentMessage {
      string example = 1;
    };
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bank-username
spec:
  memberOf: [abc-bank]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: abc-bank
spec:
  type: team
  children: []

